version: '3.9'

services:
  web:
    image: 'workshop-${IMAGE_TAG:-latest}'
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: unless-stopped
#    volumes:
#      - ./backend/asset_main:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - workshop-network

  db:
    image: 'postgres:14.0-alpine'
    restart: unless-stopped
    env_file:
      - ./docker/db/env.env
    expose:
      - 5432
    networks:
      - workshop-network
    volumes:
      - postgres:/var/lib/postgresql/data
#
#  nginx:
#    image: nginx
#    restart: 'always'
#    networks:
#      - asset-network
#    ports:
#      - 80:80
##      - 443:443
#    depends_on:
#      - cms
#    volumes:
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./backend/asset_main/static:/www/static/storage/:ro
#      - ./backend/asset_main/media:/www/media/:ro



networks:
  workshop-network:

volumes:
  postgres: