"""First

Revision ID: a757cbee6631
Revises: 
Create Date: 2022-08-03 16:10:20.198381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a757cbee6631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'user_id')
    # ### end Alembic commands ###
